version: "3"

services:
  go_server:
    build: .
    restart: always
    volumes:
    - ./main.go:/go/src/github.com/olivere/go-container-debugging/main.go
    ports:
      - "8080:8080"
      - "2345:2345"
